name: Client Unit Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: |
        cd client
        npm install
        npm run test:unit
